profile/README.md
=> docs: add img and slogan

profile/README.md
I added a temporary typing effect banner, about hacktoberfest:
[![Typing SVG](https://readme-typing-svg.herokuapp.com?size=30&vCenter=true&multiline=true&width=500&height=200&lines=%F0%9F%8E%8A+Hacktoberfest%2C+in+EddieHub!;Checkout+Our+Repos!+Contribute+NOW!+%F0%9F%8E%8A)](https://git.io/typing-svg)
thanks.
=> Added temporary hacktoberfest animated banner

README.md
=> docs: base readme

profile/README.md
Resolve #8 
@schmelto I tried to add the GIF in, if you think its in good shape, and in the right place, I will try to find a way to save the gif sort of locally on the repo itself. 
Also is this pr ok for hacktoberfest?
Thank you.
=> Added GIF.

profile/README.md
=> fix, docs: remove hacktoberfest banner

CODE_OF_CONDUCT.md
=> docs(governance): add code of conduct

README.md
=> fix: update ss

ISSUE_TEMPLATE/bug.yml, ISSUE_TEMPLATE/config.yml, ISSUE_TEMPLATE/docs.yml, ISSUE_TEMPLATE/feature_request.yml, ISSUE_TEMPLATE/other.yml
Hello, I am creating this PR regarding the issue resolve #22 .
=> Adding the issue Templates

profile/README.md
=> chore: uppercase all word

profile/README.md
=> chore: updated wording

README.md
In the `README` of this repo, the link for guide to `creating community health file` has been updated.
=> bug: Update GitHub Help link to GitHub Docs 

profile/README.md
- Update the Discord logo.
- The current logo is a modified/outdated version of the Discord logo.
The logo in this PR is the original/new version that should be used.
I don't think this applies here.
None.
=> fix: update the Discord logo

profile/README.md
=> feat: steps to get started

profile/README.md
made the necessary grammatical changes as mentioned in issue #52
-fixed grammatical errors.
=> fixed grammatical errors in  README.md

profile/README.md
=> fixed numbers next to bullet points

profile/README.md
=> docs: good first issue project

profile/README.md
=> docs: customise GitHub profile free course

.github/ISSUE_TEMPLATE/feature_request.yml
closes #66 
Update the issue form description to be more generalized.
=> fix: generalized the issue form description

profile/README.md
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
The link after point 8 is the same as point 6 so I have removed it because it is not useful
=> removed redundant link

profile/README.md
Closes #70 
profile/README had a duplication with list steps, removed bullet list (ul) and also handmade number steps, added number list (ol).
Old
> ![oldsteps](https://user-images.githubusercontent.com/62712555/209727758-f9fcf851-28d8-4fea-9fd3-9827acf63224.png)
New
> 
I deleted bullets beacuse I think last editor used numbers for steps manually, using `<ol>` have same job and semantic.
=> fix: removed duplication list steps

profile/README.md
Updated from LinkFree to BioDrop in project name
=> docs: Update the BioDrop project name
